#!/bin/bash

#SBATCH -p regular
#SBATCH -N 2
#SBATCH -t 00:30:00
#SBATCH -e mysparkjob_%j.err
#SBATCH -o mysparkjob_%j.out
#SBATCH --ccm

module load spark

start-all.sh

SPARK_HOME_DIR=/global/common/cori/software/spark/1.5.1

./bin/run --config=./config/config_ml.py 

stop-all.sh
