#!/bin/bash

#SBATCH -p regular
#SBATCH -N 2
#SBATCH -t 05:10:00
#SBATCH -e mysparkjob_%j.err
#SBATCH -o mysparkjob_%j.out
#SBATCH --ccm

module load spark

start-all.sh

./bin/run --config=./config/config_ml.py 

stop-all.sh
